# Generated by Django 5.2 on 2025-04-10 21:26

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LabourType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "base_daily_wage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Base daily wage in PKR for this labour type",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "labour_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="labour.labourtype",
                    ),
                ),
            ],
            options={
                "ordering": ["labour_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="Labourer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "cnic",
                    models.CharField(
                        help_text="Format: XXXXX-XXXXXXX-X",
                        max_length=15,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="CNIC must be in the format XXXXX-XXXXXXX-X",
                                regex="^\\d{5}-\\d{7}-\\d{1}$",
                            )
                        ],
                    ),
                ),
                ("phone", models.CharField(max_length=20)),
                ("address", models.TextField()),
                (
                    "daily_wage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Daily wage in PKR",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("emergency_contact", models.CharField(blank=True, max_length=100)),
                ("emergency_phone", models.CharField(blank=True, max_length=20)),
                ("joining_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "labour_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="labourers",
                        to="labour.labourtype",
                    ),
                ),
                (
                    "skills",
                    models.ManyToManyField(
                        blank=True, related_name="labourers", to="labour.skill"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WorkLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("work_date", models.DateField()),
                (
                    "hours_worked",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Number of hours worked",
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Additional details about work performed"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "labourer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="work_logs",
                        to="labour.labourer",
                    ),
                ),
                (
                    "tasks_performed",
                    models.ManyToManyField(
                        help_text="Skills/tasks performed during work",
                        related_name="work_logs",
                        to="labour.skill",
                    ),
                ),
            ],
            options={
                "ordering": ["-work_date"],
                "unique_together": {("labourer", "work_date")},
            },
        ),
        migrations.CreateModel(
            name="LabourPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("payment_date", models.DateField()),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("easypaisa", "Easypaisa"),
                            ("jazzcash", "JazzCash"),
                            ("bank", "Bank Transfer"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True,
                        help_text="Transaction ID for non-cash payments",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "bonus_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Additional bonus amount if any",
                        max_digits=10,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "labourer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="labour.labourer",
                    ),
                ),
                (
                    "work_logs",
                    models.ManyToManyField(
                        help_text="Work logs covered by this payment",
                        related_name="payments",
                        to="labour.worklog",
                    ),
                ),
            ],
            options={
                "ordering": ["-payment_date"],
            },
        ),
    ]
